name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - x86
        node:
          - 10
          - 12
          - 14
          - 16
          - 18
        os:
          - macOS-latest
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-2022
        exclude:
          - arch: x86
            os: macOS-latest
          - arch: x86
            os: ubuntu-22.04
          - arch: x86
            os: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
      - run: npm install
      - run: npm test
      - run:
          echo ::set-output name=job_id::$(node -e
          "console.log(crypto.randomBytes(16).toString('hex'))")
        id: get_job_id
        shell: bash
